name: bullseye_examples
description: Demonstrating Bullseye2D
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.7.2

dependencies:
  web: ^1.1.1
  bullseye2d:
    path: ../
  path: ^1.9.1
  vector_math: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.5
  lints: ^5.0.0
