name: bullseye2d
description: 2D Game Engine for Dart
version: 1.0.2
repository: https://github.com/bullseye2d/bullseye2d

executables:
  bullseye2d: bullseye2d

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  http: ^1.3.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  vector_math: ^2.1.5
  web: ^1.1.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0

